# Generated by Django 3.2.6 on 2021-08-14 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(default='assdf', upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PortfolioGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolioitem')),
            ],
        ),
    ]
