# Generated by Django 3.2.6 on 2021-08-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210814_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
