# Generated by Django 3.2.6 on 2021-08-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_email', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ('order',)},
        ),
    ]
