# Generated by Django 3.2.6 on 2021-08-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contact_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
