# Generated by Django 3.2.6 on 2021-08-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210816_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default='asdf', max_length=150),
            preserve_default=False,
        ),
    ]
