# Generated by Django 3.2.6 on 2021-08-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_gallery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
