# Generated by Django 3.2.6 on 2021-08-16 18:10

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='alt',
            field=models.CharField(default='Portfolio Image', max_length=250),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to=''),
        ),
    ]
