# Generated by Django 3.2.6 on 2021-08-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20210816_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Google',
        ),
    ]
