# Generated by Django 3.2.6 on 2021-08-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_custom_copy_item_props_to_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='portfolio_item',
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
