# Generated by Django 3.2.6 on 2021-08-17 09:32

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20210816_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='video',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=''),
        ),
    ]
