# Generated by Django 3.2.6 on 2021-08-17 11:11

from django.db import migrations
from portfolio.models import PortfolioManager, PortfolioPage


def forwards(apps, schema_editor):
    pm = PortfolioManager()
    pm.save()
    PortfolioPage.objects.all().update(portfolio=pm)


def reverse(apps, schema_editor):
    PortfolioManager.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20210817_1116'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
