# Generated by Django 3.2.6 on 2021-08-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_custom_create_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='is_thumbnail',
        ),
    ]
